<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AnimeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('animes')->truncate();

        $animes = [
            [
                'id' => 1,
                'titulo_br' => 'Fullmetal Alchemist: Brotherhood',
                'titulo_jp' => 'Hagane no Renkinjutsushi: Fullmetal Alchemist',
                'genero' => json_encode(['Ação', 'Aventura', 'Drama', 'Fantasia', 'Shounen'], JSON_UNESCAPED_UNICODE),
                'ano_lancamento' => 2009,
                'estudio' => 'Bones',
                'episodios' => 64,
                'sinopse' => 'Dois irmãos procuram a Pedra Filosofal para restaurar seus corpos após uma tentativa fracassada de transmutação humana, descobrindo uma conspiração sombria no processo.',
            ],
            [
                'id' => 2,
                'titulo_br' => 'Attack on Titan',
                'titulo_jp' => 'Shingeki no Kyojin',
                'genero' => json_encode(['Ação', 'Fantasia Sombria', 'Pós-apocalíptico', 'Shounen'], JSON_UNESCAPED_UNICODE),
                'ano_lancamento' => 2013,
                'estudio' => 'Wit Studio / MAPPA',
                'episodios' => 94,
                'sinopse' => 'Em um mundo onde a humanidade vive cercada por muralhas para se proteger de titãs devoradores de humanos, um jovem jura exterminar todos os titãs após sua cidade ser destruída.',
            ],
            [
                'id' => 3,
                'titulo_br' => 'Steins;Gate',
                'titulo_jp' => 'Steins;Gate',
                'genero' => json_encode(['Ficção Científica', 'Suspense', 'Psicológico'], JSON_UNESCAPED_UNICODE),
                'ano_lancamento' => 2011,
                'estudio' => 'White Fox',
                'episodios' => 24,
                'sinopse' => 'Um grupo de amigos descobre um método de enviar mensagens para o passado, desencadeando uma série de eventos que alteram suas linhas do tempo e os colocam em perigo.',
            ],
            [
                'id' => 4,
                'titulo_br' => 'Death Note',
                'titulo_jp' => 'Desu Nōto',
                'genero' => json_encode(['Suspense', 'Sobrenatural', 'Psicológico', 'Shounen'], JSON_UNESCAPED_UNICODE),
                'ano_lancamento' => 2006,
                'estudio' => 'Madhouse',
                'episodios' => 37,
                'sinopse' => 'Um estudante do ensino médio encontra um caderno que permite matar qualquer pessoa cujo nome seja escrito nele. Ele decide usar seu poder para criar um novo mundo livre de criminosos.',
            ],
            [
                'id' => 5,
                'titulo_br' => 'Cowboy Bebop',
                'titulo_jp' => 'Kaubōi Bibappu',
                'genero' => json_encode(['Ação', 'Aventura', 'Comédia', 'Ficção Científica', 'Espacial'], JSON_UNESCAPED_UNICODE),
                'ano_lancamento' => 1998,
                'estudio' => 'Sunrise',
                'episodios' => 26,
                'sinopse' => 'A tripulação da nave Bebop viaja pelo sistema solar em busca de recompensas. Cada membro tem um passado misterioso que é explorado ao longo da série.',
            ],
            [
                'id' => 6,
                'titulo_br' => 'Neon Genesis Evangelion',
                'titulo_jp' => 'Shin Seiki Evangerion',
                'genero' => json_encode(['Ação', 'Drama', 'Mecha', 'Psicológico'], JSON_UNESCAPED_UNICODE),
                'ano_lancamento' => 1995,
                'estudio' => 'Gainax / Tatsunoko Production',
                'episodios' => 26,
                'sinopse' => 'Em um mundo pós-apocalíptico, adolescentes são recrutados para pilotar robôs gigantes chamados Evangelions e lutar contra seres monstruosos conhecidos como Anjos.',
            ],
            [
                'id' => 7,
                'titulo_br' => 'Vinland Saga',
                'titulo_jp' => 'Vinrando Saga',
                'genero' => json_encode(['Ação', 'Aventura', 'Drama', 'Histórico', 'Seinen'], JSON_UNESCAPED_UNICODE),
                'ano_lancamento' => 2019,
                'estudio' => 'Wit Studio / MAPPA',
                'episodios' => 48,
                'sinopse' => 'Um jovem islandês busca vingança contra o homem que assassinou seu pai, envolvendo-se nos conflitos entre vikings e ingleses no século XI.',
            ],
            [
                'id' => 8,
                'titulo_br' => 'Jujutsu Kaisen',
                'titulo_jp' => 'Jujutsu Kaisen',
                'genero' => json_encode(['Ação', 'Fantasia Sombria', 'Sobrenatural', 'Shounen'], JSON_UNESCAPED_UNICODE),
                'ano_lancamento' => 2020,
                'estudio' => 'MAPPA',
                'episodios' => 47,
                'sinopse' => 'Um estudante do ensino médio se envolve com uma sociedade secreta de feiticeiros Jujutsu para eliminar uma maldição e recuperar os dedos de um demônio poderoso.',
            ],
            [
                'id' => 9,
                'titulo_br' => 'Your Name.',
                'titulo_jp' => 'Kimi no Na wa.',
                'genero' => json_encode(['Drama', 'Romance', 'Sobrenatural'], JSON_UNESCAPED_UNICODE),
                'ano_lancamento' => 2016,
                'estudio' => 'CoMix Wave Films',
                'episodios' => 1,
                'sinopse' => 'Dois adolescentes, uma garota do campo e um garoto de Tóquio, misteriosamente começam a trocar de corpo, desenvolvendo uma conexão única enquanto tentam se encontrar.',
            ],
            [
                'id' => 10,
                'titulo_br' => 'Violet Evergarden',
                'titulo_jp' => 'Vaioretto Evāgāden',
                'genero' => json_encode(['Drama', 'Fantasia', 'Slice of Life'], JSON_UNESCAPED_UNICODE),
                'ano_lancamento' => 2018,
                'estudio' => 'Kyoto Animation',
                'episodios' => 13,
                'sinopse' => "Após a guerra, uma jovem ex-soldado, criada como uma arma, começa a trabalhar como uma Autômata de Automemórias para entender as últimas palavras de seu major: 'Eu te amo'.",
            ],
            [
                'id' => 11,
                'titulo_br' => 'Demon Slayer',
                'titulo_jp' => 'Kimetsu no Yaiba',
                'genero' => json_encode(['Ação', 'Fantasia Sombria', 'Aventura', 'Shounen'], JSON_UNESCAPED_UNICODE),
                'ano_lancamento' => 2019,
                'estudio' => 'Ufotable',
                'episodios' => 55,
                'sinopse' => 'Um jovem se torna um caçador de demônios para vingar sua família e encontrar uma cura para sua irmã, que foi transformada em um demônio.',
            ],
            [
                'id' => 12,
                'titulo_br' => 'One Punch Man',
                'titulo_jp' => 'Wanpanman',
                'genero' => json_encode(['Ação', 'Comédia', 'Super-herói', 'Seinen'], JSON_UNESCAPED_UNICODE),
                'ano_lancamento' => 2015,
                'estudio' => 'Madhouse / J.C.Staff',
                'episodios' => 24,
                'sinopse' => 'Um herói tão poderoso que consegue derrotar qualquer inimigo com um único soco enfrenta uma crise existencial por não encontrar mais desafios.',
            ],
            [
                'id' => 13,
                'titulo_br' => 'My Hero Academia',
                'titulo_jp' => 'Boku no Hero Academia',
                'genero' => json_encode(['Ação', 'Comédia', 'Super-herói', 'Shounen'], JSON_UNESCAPED_UNICODE),
                'ano_lancamento' => 2016,
                'estudio' => 'Bones',
                'episodios' => 138,
                'sinopse' => 'Em um mundo onde quase todos possuem superpoderes, um garoto nascido sem eles sonha em se tornar o maior herói de todos e herda os poderes do herói número um.',
            ],
            [
                'id' => 14,
                'titulo_br' => 'Hunter x Hunter (2011)',
                'titulo_jp' => 'Hantā Hantā',
                'genero' => json_encode(['Ação', 'Aventura', 'Fantasia', 'Shounen'], JSON_UNESCAPED_UNICODE),
                'ano_lancamento' => 2011,
                'estudio' => 'Madhouse',
                'episodios' => 148,
                'sinopse' => "Um jovem chamado Gon parte em uma jornada para se tornar um 'Hunter' (caçador) e encontrar seu pai, que também é um Hunter lendário.",
            ],
            [
                'id' => 15,
                'titulo_br' => 'Code Geass: Lelouch of the Rebellion',
                'titulo_jp' => 'Kōdo Giasu: Hangyaku no Rurūshu',
                'genero' => json_encode(['Ação', 'Mecha', 'Militar', 'Suspense', 'Drama'], JSON_UNESCAPED_UNICODE),
                'ano_lancamento' => 2006,
                'estudio' => 'Sunrise',
                'episodios' => 50,
                'sinopse' => 'Um estudante exilado ganha um poder chamado Geass e lidera uma rebelião contra o Sacro Império da Britannia para criar um novo mundo.',
            ],
            [
                'id' => 16,
                'titulo_br' => 'Psycho-Pass',
                'titulo_jp' => 'Saiko Pasu',
                'genero' => json_encode(['Ação', 'Ficção Científica', 'Policial', 'Psicológico'], JSON_UNESCAPED_UNICODE),
                'ano_lancamento' => 2012,
                'estudio' => 'Production I.G',
                'episodios' => 41,
                'sinopse' => 'Em um futuro onde é possível medir a propensão de uma pessoa para o crime, detetives caçam criminosos latentes antes que eles cometam crimes.',
            ],
            [
                'id' => 17,
                'titulo_br' => 'Mob Psycho 100',
                'titulo_jp' => 'Mobu Saiko Hyaku',
                'genero' => json_encode(['Ação', 'Comédia', 'Slice of Life', 'Sobrenatural'], JSON_UNESCAPED_UNICODE),
                'ano_lancamento' => 2016,
                'estudio' => 'Bones',
                'episodios' => 37,
                'sinopse' => 'Um estudante com poderes psíquicos avassaladores tenta controlar suas emoções para não perder o controle, enquanto navega pela vida escolar.',
            ],
            [
                'id' => 18,
                'titulo_br' => 'The Promised Neverland',
                'titulo_jp' => 'Yakusoku no Nebārando',
                'genero' => json_encode(['Fantasia Sombria', 'Mistério', 'Suspense', 'Psicológico'], JSON_UNESCAPED_UNICODE),
                'ano_lancamento' => 2019,
                'estudio' => 'CloverWorks',
                'episodios' => 23,
                'sinopse' => 'Um grupo de crianças superdotadas descobre a verdade sombria sobre o orfanato em que vivem e planeja uma fuga desesperada.',
            ],
            [
                'id' => 19,
                'titulo_br' => 'A Viagem de Chihiro',
                'titulo_jp' => 'Sen to Chihiro no Kamikakushi',
                'genero' => json_encode(['Aventura', 'Fantasia', 'Sobrenatural', 'Drama'], JSON_UNESCAPED_UNICODE),
                'ano_lancamento' => 2001,
                'estudio' => 'Studio Ghibli',
                'episodios' => 1,
                'sinopse' => 'Uma menina de 10 anos se vê presa em um mundo de deuses e monstros e precisa trabalhar em uma casa de banhos para encontrar uma maneira de salvar seus pais e voltar para casa.',
            ],
            [
                'id' => 20,
                'titulo_br' => 'Mushishi',
                'titulo_jp' => 'Mushishi',
                'genero' => json_encode(['Aventura', 'Fantasia', 'Mistério', 'Slice of Life', 'Sobrenatural'], JSON_UNESCAPED_UNICODE),
                'ano_lancamento' => 2005,
                'estudio' => 'Artland',
                'episodios' => 46,
                'sinopse' => "Ginko, um 'Mushi Master', viaja para ajudar pessoas que sofrem com criaturas sobrenaturais chamadas Mushi, que podem causar doenças misteriosas.",
            ],
            [
                'id' => 21,
                'titulo_br' => 'Samurai Champloo',
                'titulo_jp' => 'Samurai Chanpurū',
                'genero' => json_encode(['Ação', 'Aventura', 'Comédia', 'Histórico', 'Samurai'], JSON_UNESCAPED_UNICODE),
                'ano_lancamento' => 2004,
                'estudio' => 'Manglobe',
                'episodios' => 26,
                'sinopse' => 'Dois espadachins errantes e uma jovem garçonete viajam pelo Japão do período Edo em busca de um samurai que cheira a girassóis.',
            ],
            [
                'id' => 22,
                'titulo_br' => 'Erased',
                'titulo_jp' => 'Boku dake ga Inai Machi',
                'genero' => json_encode(['Mistério', 'Suspense', 'Psicológico', 'Sobrenatural'], JSON_UNESCAPED_UNICODE),
                'ano_lancamento' => 2016,
                'estudio' => 'A-1 Pictures',
                'episodios' => 12,
                'sinopse' => 'Um homem com a habilidade de voltar no tempo por alguns minutos antes de um acidente é enviado 18 anos ao passado para impedir uma tragédia de sua infância.',
            ],
            [
                'id' => 23,
                'titulo_br' => 'Haikyuu!!',
                'titulo_jp' => 'Haikyū!!',
                'genero' => json_encode(['Comédia', 'Drama', 'Esporte', 'Shounen'], JSON_UNESCAPED_UNICODE),
                'ano_lancamento' => 2014,
                'estudio' => 'Production I.G',
                'episodios' => 85,
                'sinopse' => 'Inspirado por um jogador de vôlei de baixa estatura, Shoyo Hinata decide se tornar o melhor jogador, apesar de sua própria altura, e revive o clube de vôlei de sua escola.',
            ],
            [
                'id' => 24,
                'titulo_br' => "JoJo's Bizarre Adventure",
                'titulo_jp' => 'JoJo no Kimyō na Bōken',
                'genero' => json_encode(['Ação', 'Aventura', 'Sobrenatural', 'Shounen'], JSON_UNESCAPED_UNICODE),
                'ano_lancamento' => 2012,
                'estudio' => 'David Production',
                'episodios' => 190,
                'sinopse' => "A história da família Joestar e suas lutas contra forças do mal ao longo de gerações, cada parte focando em um descendente com o apelido 'JoJo'.",
            ],
            [
                'id' => 25,
                'titulo_br' => 'Kaguya-sama: Love Is War',
                'titulo_jp' => "Kaguya-sama wa Kokurasetai: Tensai-tachi no Ren'ai Zunōsen",
                'genero' => json_encode(['Comédia', 'Romance', 'Psicológico', 'Slice of Life'], JSON_UNESCAPED_UNICODE),
                'ano_lancamento' => 2019,
                'estudio' => 'A-1 Pictures',
                'episodios' => 37,
                'sinopse' => 'Dois gênios do conselho estudantil, Kaguya e Miyuki, veem o amor como uma guerra e travam batalhas psicológicas para fazer o outro confessar seus sentimentos primeiro.',
            ],
            [
                'id' => 26,
                'titulo_br' => 'Made in Abyss',
                'titulo_jp' => 'Meido in Abisu',
                'genero' => json_encode(['Aventura', 'Fantasia Sombria', 'Mistério', 'Sci-Fi'], JSON_UNESCAPED_UNICODE),
                'ano_lancamento' => 2017,
                'estudio' => 'Kinema Citrus',
                'episodios' => 25,
                'sinopse' => 'Uma jovem órfã e um robô humanóide descem a um abismo misterioso e perigoso em busca da mãe dela, enfrentando criaturas e uma maldição mortal.',
            ],
            [
                'id' => 27,
                'titulo_br' => 'Odd Taxi',
                'titulo_jp' => 'Oddo Takushī',
                'genero' => json_encode(['Mistério', 'Drama', 'Comédia'], JSON_UNESCAPED_UNICODE),
                'ano_lancamento' => 2021,
                'estudio' => 'OLM / P.I.C.S.',
                'episodios' => 13,
                'sinopse' => 'A história de um taxista morsa cínico e de suas conversas com os passageiros animais antropomórficos, que se entrelaçam em um mistério de uma garota desaparecida.',
            ],
            [
                'id' => 28,
                'titulo_br' => 'Frieren: Beyond Journey\'s End',
                'titulo_jp' => 'Sōsō no Furīren',
                'genero' => json_encode(['Aventura', 'Drama', 'Fantasia', 'Slice of Life'], JSON_UNESCAPED_UNICODE),
                'ano_lancamento' => 2023,
                'estudio' => 'Madhouse',
                'episodios' => 28,
                'sinopse' => 'Após derrotar o Rei Demônio, uma elfa imortal reflete sobre o tempo e a mortalidade enquanto revisita os lugares que percorreu com seus antigos companheiros humanos.',
            ],
            [
                'id' => 29,
                'titulo_br' => 'Cyberpunk: Edgerunners',
                'titulo_jp' => 'Saibāpanku: Ejjirannāzu',
                'genero' => json_encode(['Ação', 'Ficção Científica', 'Cyberpunk', 'Drama'], JSON_UNESCAPED_UNICODE),
                'ano_lancamento' => 2022,
                'estudio' => 'Studio Trigger',
                'episodios' => 10,
                'sinopse' => "Em uma metrópole futurista obcecada por tecnologia e modificações corporais, um jovem de rua tenta sobreviver como um mercenário conhecido como 'edgerunner'.",
            ],
            [
                'id' => 30,
                'titulo_br' => 'Bocchi the Rock!',
                'titulo_jp' => 'Bocchi za Rokku!',
                'genero' => json_encode(['Comédia', 'Música', 'Slice of Life'], JSON_UNESCAPED_UNICODE),
                'ano_lancamento' => 2022,
                'estudio' => 'CloverWorks',
                'episodios' => 12,
                'sinopse' => 'Uma guitarrista extremamente introvertida e popular na internet é inesperadamente convidada para se juntar a uma banda, forçando-a a sair de sua zona de conforto.',
            ],
        ];

        foreach ($animes as &$anime) {
            $anime['created_at'] = now();
            $anime['updated_at'] = now();
        }

        DB::table('animes')->insert($animes);
    }
}
